config/routes.rb
Rails.application.routes.draw do
  get 'welcome/privacypol'
  get 'welcome/termcondition'
  get 'welcome/howto'
  get 'welcome/aboutus'
  get 'invitations/index'
  get 'invitations/recent'
  get 'sessions/new'
  get 'articles/new'
  get 'users/profil'
  get 'welcome/index'
  get 'events/recent'
  root 'welcome#index'
  resources :users 
  resources :events do
    member do
      get 'join'
      get 'leave'
    end
  end
  resources :invitations

  post 'invitations/index'
  get '/login' =>'sessions#new'
  get '/index' =>'welcome#index'
  get '/pp' => 'welcome#privacypol'
  get '/ht' => 'welcome#howto'
  get '/au' => 'welcome#aboutus'
  get '/tc' => 'welcome#termcondition'

  post '/login' =>'sessions#create'
  # post '/login' =>'sessions#save'
  get '/logout' =>'sessions#destroy'
  get '/signup' =>'users#new'
  post '/users'=>'users#create'
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
   	 # has_many :users
	 # has_and_belongs_to_many :invitations, dependent: :destroy
	mount_uploader :files, FilesUploader



end

app/models/invitation.rb
class Invitation < ApplicationRecord
  # has_and_belongs_to_many :users, dependent: :destroy
  # has_and_belongs_to_many :events, dependent: :destroy

  def self.check event_id, user_id
  	find_by(users_id: user_id, events_id: event_id).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
# attr_accessor :image
# belongs_to :event
# has_many :events
# has_and_belongs_to_many :invitations, dependent: :destroy
mount_uploader :file, FileUploader
before_save { self.email = email.downcase}
validates :name, presence: true
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, 
			format: {with: VALID_EMAIL_REGEX},
			uniqueness: {case_sensitive: false}
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	protect_from_forgery with: :exception

	def current_user
		@current_user ||= User.find(session[:user_id])if session[:user_id]
	end
	helper_method :current_user

	def authorize
		redirect_to 'login' unless current_user
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def new
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :authorize

def index
    @events = Event.all
    @users = User.all
  end
  def recent
    @events = Event.all
    @invitations = Invitation.all
  end

  def show
    @event = Event.find(params[:id])
    @users = User.all

  end
 
  def new
    @event = Event.new
  end
 
  def edit
    @event = Event.find(params[:id])
  end
 
  def create
    
      @event = Event.create(event_params)
      # @invitation = Invitation.create(invitation_params)
      if @event.save
        redirect_to @event
      else
        render 'new'
      end
    
      # if @invitation.save
        # redirect_to @invitation
        # render 'events'
      # else
        # render 'new'
      # end
    
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params) 
      redirect_to event_path(@event)
    else
      render 'edit'
    end 
  end
 
 def join
  @event = Event.find(params[:id])
    @event.update_attribute(:users_id, @users_id)
    redirect_to @event
    
    
end

def leave
  @event = Event.find params[:id]
  current_user.update_attribute(:event_id, nil)
  redirect_to @event
end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
 
    redirect_to events_path
  end
 
  private
    def event_params
      params.require(:event).permit(:judul, :pemateri, :tag, :tgl, :waktu, :lokasi, :files, :details, :users_id)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    @events = Event.all
  	@invitations = Invitation.all
  end

  def recent
    @events = Event.all
    @invitations = Invitation.all
  end

  def show
    @event = Event.find(params[:id])
    @invitations = Invitation.all
    
  end
  
  def new
    @invitation = Invitation.new
  end



  def create
    @invitation = Invitation.new(invitation_params)
    
    if @invitation.save
      
    else
      render 'index'
    end
  end

  def edit
    @invitation = Invitation.find(params[:id])
  end

  def update
    @invitation = Invitation.find(params[:id])
    if @invitation.update(invitation_params) 
      redirect_to invitation_path(@invitation)
    else
      render 'edit'
    end 
  end

  # def destroy
  #   @invitation = Invitation.find(params[:id])
  #   @invitation.destroy


  # end
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
 
    redirect_to event_path
  end

  private
    def invitation_params
      params.require(:invitation).permit(:events_id, :users_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	user = User.find_by_email(params[:email])

  	if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/events'
    else
     	redirect_to '/welcome/index'
    end
  end
#   def save
#     user = User.find_by_email(params[:email])

#     if user && user.authenticate(params[:password])
# session[:user_id] = user.id
# redirect_to '/articles/new'
# else
#   redirect_to '/welcome/index'
#     end
#   end 
  def destroy
  	session[:user_id] = nil
  	redirect_to '/welcome/index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

  	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
			redirect_to '/events'
		else
			redirect_to '/welcome/index'
		end
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to '/users/profil'
		else
			render 'edit'
		end
	end

private
	def user_params
		params.require(:user).permit(:name,:email, :password, :password_confirmation, :file, :instansi, :minat, :level)		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@events = Event.last(4)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/show.html.erb
<%if current_user%>
<div class="navbar navbar-expand-lg navbar-light" style="background-color: #FBFDFD" >
  <div class="navbar-brand" id="bor"><%=link_to image_tag("logo.png", width:"80px"), '/welcome/index'%></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContent" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
          <a id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%=link_to 'Events', '/events', class: 'nav-link'%>
        </a>
    </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item ">
      
      </li>
    <li class="nav-item">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag current_user.file_url,class: 'img-circle1' %>
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"><center><%=current_user.name%></center></a>
          <div class="dropdown-divider"></div>
          <center><%=link_to 'Profil', '/users/profil' , class: 'dropdown-item'%></center>
          <center><%=link_to "Logout",'/logout' ,class: 'dropdown-item'%></center>
        </div>
      </li>
    </li>
  </ul>
</div>
</div>
<hr>
<div class="row" style="margin-top: -1.5%">
<div class="col-md-12">
    <div class="card" id="jar">
      <div class="card-header" style="padding: 25px;"><div style="margin-left: 2%; margin-bottom: 0.4%"><%= @event.tgl%></div><h3 style="width: 60%; margin-bottom: -5%"><%=@event.judul%></h3>

      <%= form_for :invitation, url: invitations_path do |form|%>
<%=form.hidden_field :events_id, value: @event.id%><br>
<%=form.hidden_field :users_id, value: current_user.id%><br>
<% if Invitation.check(@event.id, current_user.id) %>
  <%=form.submit 'Join', class: 'btn btn-danger kananbutton disabled', style: 'float:right; margin-top: -4%;'%>
<% else %>
  <%=form.submit 'Join', class: 'btn btn-danger kananbutton'  , style: 'float:right; margin-top: -4%;', data: { confirm: 'Are you sure?' }%>
<% end %>
<%end%>

    </div>
        <div class="card-body bg-secondary" style="padding-top: 1%; padding-left: 3%">
        <%= image_tag @event.files_url(:play)%>
        <div class="card" style="float: right; width: 23%">
          <%= image_tag ('clock.png'), style:'width:15px;'%><div style="float: left;"> <%= @event.tgl%> <%= @event.waktu%></div>
          <br> 
          <%= image_tag ('marker.png'), style:'width:10px;'%><%= @event.lokasi%>
        </div>
        <div style="width: 78%; margin-top: 1%">
          <%= @event.details%>
        </div>
      <div></div>
<div align="left" style="float: right; margin-top: 1%; width: 30%">
  <%if current_user.level == '0'%>
<%=link_to 'Edit', edit_event_path(@event), class: 'btn btn-danger', style: 'margin-right:3%'%>
<%else%>
<%end%>
<%= link_to 'Back', events_path, class: 'btn btn-danger'%> 
</div>   

        </div>



 
   </div>
    </div>

</div>

</div>
<div class="bottom">
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #707070">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContentfoot" aria-controls="navbarSupportedContentfoot" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContentfoot" align="center">
  <ul class="navbar-nav mr-auto">
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item" style=" color: white">
      <%= link_to  'About Us', '../au', class: 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to  'How To Join', '../ht', class: 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to  'Term & Conditions', '../tc', class: 'nav-link'%>
      <!-- <a class="nav-link" href="#">Term & Conditions<span class="sr-only">(current)</span></a> -->
    </li>
    <li class="nav-item">
      <%= link_to  'Privacy Policy', '../pp', class: 'nav-link'%>
      <!-- <a class="nav-link" href="#">Privacy Policy<span class="sr-only">(current)</span></a> -->
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    
  </ul>
</div>
</div>
</div>
      <%else%>
     <div class="navbar navbar-expand-lg navbar-light" style="background-color: #FBFDFD" id="nav-bar-header-index">
  <div class="navbar-brand" id="bor">
    <%= link_to '../index' do %>
    <%= image_tag("logo.png", width:"80px")%><% end %></div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" id="Toggle-header-index">
    <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContent" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to 'Events', '../events', class: 'nav-link'%>
    </li>
  </ul>

  <ul class="navbar-nav">
    <li class="nav-item ">
      
     
      <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sign in/Sign up
        </a>
     <div class="dropdown-menu dropdown-menu-right">
            <div class="px-4 py-3">
              <%=form_with url: login_path do |a| %>
                Email
                <div class="form-group">
                  <%= a.text_field :email, class: 'form-control' %>
                </div>
                Password
                <div class="form-group">
                  <%= a.password_field :password, class: 'form-control'%>
                </div>
                
                <div class="form-group">
                  <%= submit_tag 'Login', class: 'btn btn-danger'%>
                </div>
              <%end%>         
            </div>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" >New around here?<a type="button" class="btn btn-primary dropdown-item" data-toggle="modal" data-target="#exampleModalCenter">Sign up</a></a>
      </div> 
              <div class="modal fade bd-example-modal-lg" style="display: none; /*border: 1px solid black;*/ " id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="myLargeModallabelTitle" aria-hidden="true">
                <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalCenterTitle"><center>Ragister</center></h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body" style="width: 100%; height: 100%;">
                      <%=form_for :user, url: '/users' do |f|%>
                      <div align="left">Full Name</div>
                      <div class="form-group">
                      <%=f.text_field :name, class: 'form-control'%>
                      </div>
                      <div align="left">Email</div>
                      <div class="form-group">
                      <%=f.text_field :email, class: 'form-control'%>
                      </div>
                      <div align="left">Password</div> 
                      <div class="form-group">
                      <%=f.password_field :password, class: 'form-control'%>
                      </div>
                      <div align="left">Password Confirmation</div>
                      <div class="form-group">
                      <%=f.password_field :password_confirmation, class: 'form-control'%>
                      </div>
                      <div class="form-group">
                      <%=f.file_field :file%>
                      </div>
                      <div align="right">
                      <%=f.submit"Daftar", class: 'btn btn-danger'%>
                      </div>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
    </li>
  </ul>
</div>
</div>
</end>

<hr>
<div class="row" style="margin-top: -1.5%">
<div class="col-md-12">
    <div class="card" id="jar">
      <div class="card-header" style="padding: 25px;"><div style="margin-left: 2%; margin-bottom: 0.4%"><%= @event.tgl%></div><h3 style="width: 60%; margin-bottom: -2%"><%=@event.judul%></h3>
          <div class="kanan" style="margin-top: -2%">Silahkan Login Untuk<br>Mengikuti Event</div>
    </div>
        <div class="card-body bg-secondary" style="padding-top: 1%; padding-left: 3%">
        <%= image_tag @event.files_url(:play)%>
        <div class="card" style="float: right; width: 23%">
          <%= image_tag ('clock.png'), style:'width:15px;'%><div style="float: left;"> <%= @event.tgl%> <%= @event.waktu%></div>
          <br> 
          <%= image_tag ('marker.png'), style:'width:10px;'%><%= @event.lokasi%>
        </div>
        <div style="width: 78%; margin-top: 1%">
          <%= @event.details%>
        </div>
<div align="left" style="float: right; margin-top: 1%; width: 30%">

<%= link_to 'Back', events_path, class: 'btn btn-danger'%> 
</div>   

        </div>



 
   </div>
    </div>

</div>

</div>
<div class="bottom">
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #707070">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContentfoot" aria-controls="navbarSupportedContentfoot" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContentfoot" align="center">
  <ul class="navbar-nav mr-auto">
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item" style=" color: white">
      <%= link_to  'About Us', '../au', class: 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to  'How To Join', '../ht', class: 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to  'Term & Conditions', '../tc', class: 'nav-link'%>
      <!-- <a class="nav-link" href="#">Term & Conditions<span class="sr-only">(current)</span></a> -->
    </li>
    <li class="nav-item">
      <%= link_to  'Privacy Policy', '../pp', class: 'nav-link'%>
      <!-- <a class="nav-link" href="#">Privacy Policy<span class="sr-only">(current)</span></a> -->
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    
  </ul>
</div>
</div>
</div>
      <%end%>

app/views/invitations/show.html.erb
<%if current_user%>
<div class="navbar navbar-expand-lg navbar-light" style="background-color: #FBFDFD" >
  <div class="navbar-brand" id="bor"><%=link_to image_tag("logo.png", width:"80px"), '/welcome/index'%></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContent" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
          <a id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%=link_to 'Events', '/events', class: 'nav-link'%>
        </a>
    </li>
    <li class="nav-item">
          <a href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= link_to 'Articles', '/articles/new',class: 'nav-link'%>
        </a>
    </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item ">
      
      </li>
    <li class="nav-item">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag current_user.file_url,class: 'img-circle1' %>
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"><center><%=current_user.name%></center></a>
          <div class="dropdown-divider"></div>
          <center><%=link_to 'Profil', '/users/profil' , class: 'dropdown-item'%></center>
          <center><%=link_to "Logout",'/logout' ,class: 'dropdown-item'%></center>
        </div>
      </li>
    </li>
  </ul>
</div>
</div>
<hr>
<div class="row" style="margin-top: -1.5%">
<div class="col-md-12">
    <div class="card" id="jar">
      <div class="card-header" style="padding: 25px;"><div style="margin-left: 2%; margin-bottom: 0.4%"><%= @event.tgl%></div><h3 style="width: 60%; margin-bottom: -5%"><%=@event.judul%></h3>

      <%= form_for :invitation, url: invitations_path do |form|%>
<%=form.hidden_field :events_id, value: @event.id%><br>
<%=form.hidden_field :users_id, value: current_user.id%><br>
<% if current_user.id == %>
  <%=form.submit 'Join', class: 'btn btn-danger kananbutton', style: 'float:right; margin-top: -4%;'%>
<% else %>
  <%=form.submit 'Join', class: 'btn btn-danger kananbutton disabled'  , style: 'float:right; margin-top: -4%;'%>
<% end %>
<%end%>

    </div>
        <div class="card-body bg-secondary" style="padding-top: 1%; padding-left: 3%">
        <%= image_tag @event.files_url(:play)%>
        <div class="card" style="float: right; width: 23%">
          <%= image_tag ('clock.png'), style:'width:15px;'%><div style="float: left;"> <%= @event.tgl%> <%= @event.waktu%></div>
          <br> 
          <%= image_tag ('marker.png'), style:'width:10px;'%><%= @event.lokasi%>
        </div>
        <div style="width: 78%; margin-top: 1%">
          <%= @event.details%>
        </div>
<div align="left" style="float: right; margin-top: 1%; width: 30%">

<%= link_to 'Back', events_path, class: 'btn btn-danger'%> 
</div>   

        </div>



 
   </div>
    </div>

</div>

</div>
<div class="bottom">
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #707070">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContentfoot" aria-controls="navbarSupportedContentfoot" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContentfoot" align="center">
  <ul class="navbar-nav mr-auto">
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">About Us<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">How To Join<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Term & Conditions<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Privacy Policy<span class="sr-only">(current)</span></a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    
  </ul>
</div>
</div>
</div>
      <%else%>
      <div class="navbar navbar-expand-lg navbar-light" style="background-color: #FBFDFD" >
  <div class="navbar-brand" id="bor"><%=link_to image_tag("logo.png", width:"80px"), '/welcome/index'%></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContent" align="center">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
          <a id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%=link_to 'Events', '/events', class: 'nav-link'%>
        </a>
    </li>
    <li class="nav-item">
          <a href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= link_to 'Articles', '/articles/new',class: 'nav-link'%>
        </a>
    </li>
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item ">
      
      </li>
    <li class="nav-item">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" id="jk" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag current_user.file_url,class: 'img-circle1' %>
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item"><center><%=current_user.name%></center></a>
          <div class="dropdown-divider"></div>
          <center><%=link_to 'Profil', '/users/profil' , class: 'dropdown-item'%></center>
          <center><%=link_to "Logout",'/logout' ,class: 'dropdown-item'%></center>
        </div>
      </li>
    </li>
  </ul>
</div>
</div>
<hr>
<div class="row" style="margin-top: -1.5%">
<div class="col-md-12">
    <div class="card" id="jar">
      <div class="card-header" style="padding: 25px;"><div style="margin-left: 2%; margin-bottom: 0.4%"><%= @event.tgl%></div><h3 style="width: 60%; margin-bottom: -5%"><%=@event.judul%></h3>

      <%= form_for :invitation, url: invitations_path do |form|%>
<%=form.hidden_field :events_id, value: @event.id%><br>
<%=form.hidden_field :users_id, value: current_user.id%><br>
<% if current_user.id == %>
  <%=form.submit 'Join', class: 'btn btn-danger kananbutton disabled', style: 'float:right; margin-top: -4%;', data: {confirm: Belum Memiliki Akun}%>
<% else %>
  <%=form.submit 'Join', class: 'btn btn-danger kananbutton disabled'  , style: 'float:right; margin-top: -4%;'%>
<% end %>
<%end%>

    </div>
        <div class="card-body bg-secondary" style="padding-top: 1%; padding-left: 3%">
        <%= image_tag @event.files_url(:play)%>
        <div class="card" style="float: right; width: 23%">
          <%= image_tag ('clock.png'), style:'width:15px;'%><div style="float: left;"> <%= @event.tgl%> <%= @event.waktu%></div>
          <br> 
          <%= image_tag ('marker.png'), style:'width:10px;'%><%= @event.lokasi%>
        </div>
        <div style="width: 78%; margin-top: 1%">
          <%= @event.details%>
        </div>
<div align="left" style="float: right; margin-top: 1%; width: 30%">

<%= link_to 'Back', events_path, class: 'btn btn-danger'%> 
</div>   

        </div>



 
   </div>
    </div>

</div>

</div>
<div class="bottom">
<div class="navbar navbar-expand-lg navbar-dark" style="background-color: #707070">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContentfoot" aria-controls="navbarSupportedContentfoot" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

<div class="collapse navbar-collapse"  id="navbarSupportedContentfoot" align="center">
  <ul class="navbar-nav mr-auto">
  </ul>
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">About Us<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">How To Join<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Term & Conditions<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="#">Privacy Policy<span class="sr-only">(current)</span></a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    
  </ul>
</div>
</div>
</div>
      <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KomoDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/show.html.erb
<%=@user.name%>
<%=@user.email%>
<%@user.instansi%>
<%@user.minat%>
<%=link_to 'Edit', edit_user_path(@user)%>